//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UV_DLP_3D_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UV_DLP_3D_Printer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _9_4_2013_12_40_20_PM {
            get {
                object obj = ResourceManager.GetObject("9-4-2013 12-40-20 PM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _9_6_2013_12_05_11_AM {
            get {
                object obj = ResourceManager.GetObject("9-6-2013 12-05-11 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _9_6_2013_12_05_50_AM {
            get {
                object obj = ResourceManager.GetObject("9-6-2013 12-05-50 AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap animatedTurningHelix {
            get {
                object obj = ResourceManager.GetObject("animatedTurningHelix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bfzn_003 {
            get {
                object obj = ResourceManager.GetObject("bfzn_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bfzn_004 {
            get {
                object obj = ResourceManager.GetObject("bfzn_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bfzn_006 {
            get {
                object obj = ResourceManager.GetObject("bfzn_006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap butMinus {
            get {
                object obj = ResourceManager.GetObject("butMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttAddSupport {
            get {
                object obj = ResourceManager.GetObject("buttAddSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttAutoDown {
            get {
                object obj = ResourceManager.GetObject("buttAutoDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttAutoSupport {
            get {
                object obj = ResourceManager.GetObject("buttAutoSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttBoundingBox {
            get {
                object obj = ResourceManager.GetObject("buttBoundingBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttCenter {
            get {
                object obj = ResourceManager.GetObject("buttCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttChecked {
            get {
                object obj = ResourceManager.GetObject("buttChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttConnect {
            get {
                object obj = ResourceManager.GetObject("buttConnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttConsole {
            get {
                object obj = ResourceManager.GetObject("buttConsole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttDisconnect {
            get {
                object obj = ResourceManager.GetObject("buttDisconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttDownward {
            get {
                object obj = ResourceManager.GetObject("buttDownward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttGear {
            get {
                object obj = ResourceManager.GetObject("buttGear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttIntersect {
            get {
                object obj = ResourceManager.GetObject("buttIntersect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttMeshTools {
            get {
                object obj = ResourceManager.GetObject("buttMeshTools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttMove {
            get {
                object obj = ResourceManager.GetObject("buttMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttOinfo {
            get {
                object obj = ResourceManager.GetObject("buttOinfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttOnPlatform {
            get {
                object obj = ResourceManager.GetObject("buttOnPlatform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttOpenClose {
            get {
                object obj = ResourceManager.GetObject("buttOpenClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttOpenFile {
            get {
                object obj = ResourceManager.GetObject("buttOpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPause {
            get {
                object obj = ResourceManager.GetObject("buttPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPCone {
            get {
                object obj = ResourceManager.GetObject("buttPCone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPCube {
            get {
                object obj = ResourceManager.GetObject("buttPCube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPCylinder {
            get {
                object obj = ResourceManager.GetObject("buttPCylinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPlay {
            get {
                object obj = ResourceManager.GetObject("buttPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPlus {
            get {
                object obj = ResourceManager.GetObject("buttPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPrevDisp {
            get {
                object obj = ResourceManager.GetObject("buttPrevDisp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPSphere {
            get {
                object obj = ResourceManager.GetObject("buttPSphere", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPTorus {
            get {
                object obj = ResourceManager.GetObject("buttPTorus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttRedo {
            get {
                object obj = ResourceManager.GetObject("buttRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttRotate {
            get {
                object obj = ResourceManager.GetObject("buttRotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSave {
            get {
                object obj = ResourceManager.GetObject("buttSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttScale {
            get {
                object obj = ResourceManager.GetObject("buttScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttShowslice {
            get {
                object obj = ResourceManager.GetObject("buttShowslice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttShowsliceh {
            get {
                object obj = ResourceManager.GetObject("buttShowsliceh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSlice {
            get {
                object obj = ResourceManager.GetObject("buttSlice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttStop {
            get {
                object obj = ResourceManager.GetObject("buttStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSubtract {
            get {
                object obj = ResourceManager.GetObject("buttSubtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSupport {
            get {
                object obj = ResourceManager.GetObject("buttSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttTransparent {
            get {
                object obj = ResourceManager.GetObject("buttTransparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttTreeview {
            get {
                object obj = ResourceManager.GetObject("buttTreeview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttUndo {
            get {
                object obj = ResourceManager.GetObject("buttUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttUnion {
            get {
                object obj = ResourceManager.GetObject("buttUnion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttV {
            get {
                object obj = ResourceManager.GetObject("buttV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttView {
            get {
                object obj = ResourceManager.GetObject("buttView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttViewDown {
            get {
                object obj = ResourceManager.GetObject("buttViewDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttViewGcode {
            get {
                object obj = ResourceManager.GetObject("buttViewGcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttViewModel {
            get {
                object obj = ResourceManager.GetObject("buttViewModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttViewSlice {
            get {
                object obj = ResourceManager.GetObject("buttViewSlice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;fontMetrics file=&quot;Texture.png&quot;&gt;
        ///  &lt;character key=&quot;32&quot;&gt;
        ///    &lt;x&gt;0&lt;/x&gt;
        ///    &lt;y&gt;0&lt;/y&gt;
        ///    &lt;width&gt;9&lt;/width&gt;
        ///    &lt;height&gt;24&lt;/height&gt;
        ///  &lt;/character&gt;
        ///  &lt;character key=&quot;33&quot;&gt;
        ///    &lt;x&gt;9&lt;/x&gt;
        ///    &lt;y&gt;0&lt;/y&gt;
        ///    &lt;width&gt;7&lt;/width&gt;
        ///    &lt;height&gt;24&lt;/height&gt;
        ///  &lt;/character&gt;
        ///  &lt;character key=&quot;34&quot;&gt;
        ///    &lt;x&gt;16&lt;/x&gt;
        ///    &lt;y&gt;0&lt;/y&gt;
        ///    &lt;width&gt;10&lt;/width&gt;
        ///    &lt;height&gt;24&lt;/height&gt;
        ///  &lt;/character&gt;
        ///  &lt;character key=&quot;35&quot;&gt;
        ///    &lt;x&gt;26&lt;/x&gt;
        ///    &lt;y&gt;0&lt;/y&gt;
        ///    &lt;width&gt;14&lt;/width&gt;
        ///    &lt;height&gt;24&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Calibri22_metrics {
            get {
                return ResourceManager.GetString("Calibri22_metrics", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap checkRect {
            get {
                object obj = ResourceManager.GetObject("checkRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Connect {
            get {
                object obj = ResourceManager.GetObject("Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon cwlogo_dl {
            get {
                object obj = ResourceManager.GetObject("cwlogo_dl", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cwlogo_round {
            get {
                object obj = ResourceManager.GetObject("cwlogo_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cwtexture1 {
            get {
                object obj = ResourceManager.GetObject("cwtexture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///cwtexture1.png
        ///format: RGBA8888
        ///filter: Linear,Linear
        ///repeat: none
        ///Calibri22
        ///  rotate: false
        ///  xy: 1, 103
        ///  size: 221, 144
        ///  orig: 221, 144
        ///  offset: 0, 0
        ///  index: -1
        ///glButtHome
        ///  rotate: false
        ///  xy: 224, 183
        ///  size: 256, 64
        ///  orig: 256, 64
        ///  offset: 0, 0
        ///  index: -1
        ///cwlogo_round
        ///  rotate: false
        ///  xy: 1, 1
        ///  size: 100, 100
        ///  orig: 100, 100
        ///  offset: 0, 0
        ///  index: -1
        ///trimpanel
        ///  rotate: false
        ///  xy: 103, 11
        ///  size: 90, 90
        ///  orig: 90, 90
        ///  offset: 0, 0
        ///  index: -1
        ///.
        /// </summary>
        public static string cwtexture1_index {
            get {
                return ResourceManager.GetString("cwtexture1_index", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Disconnect {
            get {
                object obj = ResourceManager.GetObject("Disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap donate {
            get {
                object obj = ResourceManager.GetObject("donate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Donate1 {
            get {
                object obj = ResourceManager.GetObject("Donate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Down1Blue {
            get {
                object obj = ResourceManager.GetObject("Down1Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;GuiConfig FileVersion=&quot;1&quot;&gt;
        ///	&lt;buttons&gt;
        ///		&lt;theme backcolor=&quot;Royalblue&quot; forecolor=&quot;White&quot;/&gt;
        ///		&lt;button name=&quot;home&quot; dock=&quot;tr&quot; x=&quot;10&quot; y=&quot;10&quot; image=&quot;glButtHome&quot; w=&quot;48&quot; h=&quot;48&quot; gl=&quot;true&quot;/&gt;
        ///		&lt;button name=&quot;undo&quot; dock=&quot;tl&quot; x=&quot;10&quot; y=&quot;10&quot; image=&quot;buttUndo&quot; w=&quot;48&quot; h=&quot;48&quot;/&gt;
        ///		&lt;button name=&quot;redo&quot; dock=&quot;tl&quot; x=&quot;60&quot; y=&quot;10&quot; image=&quot;buttRedo&quot; w=&quot;48&quot; h=&quot;48&quot;/&gt;
        ///		&lt;button name=&quot;meshop&quot; dock=&quot;bl&quot; x=&quot;288&quot; y=&quot;10&quot; image=&quot;buttMeshTools&quot; check=&quot;checkRect&quot; w=&quot;48&quot; h=&quot;48&quot;/&gt;
        ///		&lt;button name=&quot;view&quot; dock=&quot;b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GuiConfig {
            get {
                return ResourceManager.GetString("GuiConfig", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap homeButt {
            get {
                object obj = ResourceManager.GetObject("homeButt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Left1Blue {
            get {
                object obj = ResourceManager.GetObject("Left1Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Load {
            get {
                object obj = ResourceManager.GetObject("Load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap move_bgnd {
            get {
                object obj = ResourceManager.GetObject("move_bgnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap niceAnimatedTriangles {
            get {
                object obj = ResourceManager.GetObject("niceAnimatedTriangles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap paypal_donate_button {
            get {
                object obj = ResourceManager.GetObject("paypal-donate-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap position {
            get {
                object obj = ResourceManager.GetObject("position", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Refresh_icon {
            get {
                object obj = ResourceManager.GetObject("Refresh-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Right1Blue {
            get {
                object obj = ResourceManager.GetObject("Right1Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rounded_blue_home_button_4805 {
            get {
                object obj = ResourceManager.GetObject("rounded_blue_home_button_4805", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap slice {
            get {
                object obj = ResourceManager.GetObject("slice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap turningGear {
            get {
                object obj = ResourceManager.GetObject("turningGear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Up1Blue {
            get {
                object obj = ResourceManager.GetObject("Up1Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
